---
  apiVersion: v1
  kind: Service
  metadata:
      name: sparklemiddleware-service
  spec:
      type: ClusterIP
      selector:
          app: sparklemiddleware
      ports:
          - protocol: "TCP"
            port: 8088
            targetPort: 3000
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: sparklemiddleware
spec:
    selector:
      matchLabels:
        app: sparklemiddleware
    replicas: 1
    template:
      metadata:
        labels:
          app: sparklemiddleware
      spec:
        containers:
        - name: sparklemiddleware
          image: us.icr.io/sparkle-release/sparklemiddleware:latest
          ports:
            - containerPort: 3000
          env:
            - name: HELIUMUPLOADS
              value: "heliumuploads-rel"
            - name: HELIUMWIREFRAMES
              value: "heliumwireframes-rel"
            - name: CISGOFANCYUPLOADS
              value: "cisgofancyuploads-rel"
            - name: CISGOUPLOADS
              value: "cisgouploads-rel"
            - name: CISGOZIPUPLOADS
              value: "cisgozipuploads-rel"
            - name: DIBOXFANCYUPLOADS
              value: "diboxfancyuploads-rel"
            - name: DIBOXUPLOADS
              value: "diboxuploads-rel"         
            - name: CUTWISEZIPUPLOADS
              value: "cutwisezipuploads-rel"
            - name: SPARKLEPLOTS
              value: "sparkleplots-rel"
            - name: SPARKLETABLEDATA
              value: "sparkletabledata-rel"
            - name: C-MODELS
              value: "c-models-rel"
            - name: I-MODELS
              value: "i-models-rel"
            - name: F-MODELS
              value: "f-models-rel"
            - name: AR-MODELS
              value: "ar-models-rel"
            - name: WIREFRAME-MODELS
              value: "wireframe-models-rel"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: SECRET_KEY
            - name: CISGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: CISGO_PASSWORD
            - name: CLOUDANT_ACCOUNT_URL
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: CLOUDANT_ACCOUNT_URL
            - name: CLOUDANT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: CLOUDANT_API_KEY
            - name: CLOUDANT_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: CLOUDANT_ACCOUNT_NAME
            - name: COS_AUTH_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: COS_AUTH_ENDPOINT
            - name: COS_SERVICEINSTANCE_ID
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: COS_SERVICEINSTANCE_ID
            - name: COS_API_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: COS_API_KEY_ID
            - name: COS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: COS_ENDPOINT
            - name: APPID_TENANTID
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: APPID_TENANTID
            - name: APPID_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: APPID_CLIENTID
            - name: APPID_SECRET
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: APPID_SECRET
            - name: APPID_OAUTHSERVERURL
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: APPID_OAUTHSERVERURL
            - name: APPID_CUTWISE_OAUTHSERVERURL
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: APPID_CUTWISE_OAUTHSERVERURL
            - name: APPID_REDIRECTURL
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: APPID_REDIRECTURL
            - name: RABBITMQ_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: RABBITMQ_CONNECTION
            - name: RABBITMQ_CERTIFICATE_BASE64
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: RABBITMQ_CERTIFICATE_BASE64
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: RABBITMQ_PORT
            - name: RABBITMQ_BINDING
              valueFrom:
                secretKeyRef:
                  name: deployment-secret
                  key: RABBITMQ_BINDING
        nodeSelector:
          node: 10.221.145.91