apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
 name: sparkleingressresource
 annotations:
    kubernetes.io/ingress.class: "public-iks-k8s-nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 160s
    nginx.ingress.kubernetes.io/proxy-read-timeout: 160s
spec:
 tls:
 - hosts:
   - sparklepipelinecluster-0de26d204cce5ce3782ab0318a20cdb8-0000.us-south.containers.appdomain.cloud
   secretName: sparklepipelinecluster-0de26d204cce5ce3782ab0318a20cdb8-0000
 rules:
 - host: sparklepipelinecluster-0de26d204cce5ce3782ab0318a20cdb8-0000.us-south.containers.appdomain.cloud
   http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: sparklemiddleware-service
          servicePort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
 name: sparkleingressresource-hub
 annotations:
  kubernetes.io/ingress.class: "public-iks-k8s-nginx"
  nginx.ingress.kubernetes.io/proxy-body-size: 20m
  nginx.ingress.kubernetes.io/proxy-connect-timeout: 160s
  nginx.ingress.kubernetes.io/proxy-read-timeout: 160s
  nginx.ingress.kubernetes.io/whitelist-source-range: 44.235.61.164, 44.227.66.214, 52.25.4.215, 52.24.212.160
spec:
 tls:
 - hosts:
   - sparklepipelinecluster-0de26d204cce5ce3782ab0318a20cdb8-0000.us-south.containers.appdomain.cloud
   secretName: sparklepipelinecluster-0de26d204cce5ce3782ab0318a20cdb8-0000
 rules:
 - host: sparklepipelinecluster-0de26d204cce5ce3782ab0318a20cdb8-0000.us-south.containers.appdomain.cloud
   http:
      paths:     
      - path: /hub
        pathType: Prefix
        backend:
          serviceName: proxy-public
          servicePort: 80
      - path: /hub/
        pathType: Prefix
        backend:
          serviceName: proxy-public
          servicePort: 80
      - path: /user/
        pathType: Prefix
        backend:
          serviceName: proxy-public
          servicePort: 80

